Feature tictactoe
pipe2442/tictactoe_javascript pull request #1
Opened 2021-05-27 16:58 UTC by pipe2442

Tic-tac-toe - Javascript

This branch was created to merge tic tac toe feature and functions with javascript.

- Created Html, CSS and JavaScript base.
- Created functions to store board in an array and loop the game.
- Created buttonto start the game and restart when win casses occur.
- Add styling with css and linters with stylelintrc.json.

2021-05-27 18:45 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Game UI is very appealing.
- [ ] You have mastered Git flow.
- [ ] PR title and summary are descriptive.
- [ ] README provides all the necessary info about the repository.

## To Improve 🙏
- [ ] Please see inline comments for reference.
- [ ] You should not use global code. Please encapsulate logic inside modules or factories. See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/global_requirement.png).
- [ ] Please use game, gameBoard, player objects. See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/objects_requirement.png).
- [ ] Game should allow players to enter their names.
- [ ] Please uses an array inside of a gameBoard object to store the 'moves'.
- [ ] Players should be stored as objects. See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/objects_requirement.png).
- [ ] Application logic should be separated from DOM manipulation tasks.
# Optional
- [ ] You can use [Netlify](https://www.netlify.com/) to host your app.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-05-27 18:45 UTC, SajjadAhmad14 commented on app.js
> +const cells = document.querySelectorAll('.cell');
Please try avoiding global code.

2021-05-27 18:45 UTC, SajjadAhmad14 commented on app.js
> +        document.getElementById('win').innerHTML = '<h1>That\'s not a valid move!!!</h1>';
DOM manipulation should not be mixed up with app logic.

2021-06-01 17:46 UTC, pipe2442 commented
Thanks for the previews review, changes has been implemented.

2021-06-01 18:28 UTC, MkrtichSargsyan requested changes
## _Status:_ Changes Requested :recycle:

## Hello Guys

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:

## To Highlight :tada:


1. Your PR has a good title and description.
2. You have descriptive git commit messages.


Good job on implementing the changes requested. However, there are some changes that you need to make in order to get your project approved

- [ ] It has game, gameBoard, player objects [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/global_requirement.png)

- [x] It doesn't show if the move is a tie

![err](https://user-images.githubusercontent.com/31889642/120372652-8147b300-c328-11eb-9f5c-b1304cdcbee7.png)


- [ ] Please validate user input, so the usernames should not be empty

- [ ] Don't disable that much eslint-rules


<hr>

## OPTIONAL

- [ ] Kindly find a way to make the checkWinner function cleaner

Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

2021-06-01 18:31 UTC, MkrtichSargsyan commented on app.js
> +      } else if (turnNumber % 2 !== 0) {
No need for else if, just write else

2021-06-01 18:32 UTC, MkrtichSargsyan commented on app.js
> +    } else if (turnNumber % 2 !== 0) {
instead of else if you can write else without any condition

2021-06-01 22:57 UTC, pipe2442 commented
Thanks for the review, the project was fixed with requested changes.

2021-06-02 00:17 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-06-02 00:19 UTC, merged